markdown: redcarpet
pygments: true
project_name: Highcharts4gwt
project_snapshot_version: 0.0-SNAPSHOT
project_version: 0.1
project_versions: [0.1]
github_page: https://github.com/highcharts4gwt/
demo_page: http://data-dragon-766.appspot.com/
